---
server:
    port: 8095
spring:
    application:
        name: product-resource
    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: http://localhost:9001
