---
server:
    port: 8096
spring:
    application:
        name: order-client
    security:
        oauth2:
            client:
                registration:
                    order-client:
                        provider: order-provider
                        client-id: order-client
                        client-secret: order-client-secret
                        authorization-grant-type: client_credentials
                        scope:
                            - openid
                provider:
                    order-provider:
                        token-uri: http://localhost:9001/oauth2/token
