server:
  port: 9000
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: catalogService
              uri: http://product-catalog:8081
              predicates:
                - Path= /catalog/**
              filters:
                - AddRequestHeader=X-catalog-header,productcatalog
                - AddResponseHeader=X-catalog-responsetime,"#{T(java.time.LocalDate).now()}"
                - RewritePath=/catalog/(?<segment>.*),/catalog-service/v1/${segment}
            - id: info-service
              uri: http://product-info:8082
              predicates:
                - Path= /info/**
              filters:
                - AddRequestHeader=X-info-header,productinfo
                - AddResponseHeader=X-info-responsetime,"#{T(java.time.LocalDate).now()}"
                - RewritePath=/info/(?<segment>.*),/info-service/v1/${segment}
