## Data-Source specific properties (now available via config-server)
#spring:
#    datasource:
#        url: jdbc:mysql://localhost:3306/jfsseptkart?rewriteBatchedStatements=true
#        username: root
#        password: manish
#    jpa:
#        show-sql: true
#        hibernate:
#            ddl-auto: update

spring:
    application:
        name: product-catalog
    config:
        import:
            - configserver:http://config-server:8888
    profiles:
        default: default
        active:
            - dev

server:
    port: 8081

management:
    endpoints:
        web:
            base-path: /custom-actuator-path
            exposure:
                include:
                    - "*"
    endpoint:
        health:
            show-details: always
